---
name: Build and Deploy webapp

env:
  #Artifact Name: csye6225-webapp-${{github.run_number}}.zip
  ARTIFACT_NAME: csye6225-webapp-${{github.run_number}}.zip
  CODEDEPLOY_APPLICATION_NAME: mywebapp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: mywebapp
  AWS_REGION: us-west-2

on:
  push:
      branches: [ main ]

jobs:
  ci_cd:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with: 
          java-version: 1.8
      - name: Build with maven
        run: |
          echo "${{env.ARTIFACT_NAME}}"
          pwd
          ls
          mvn clean install
          pwd
          ls -al
          ls -al build/libs
      - name: Build Deployemnt Artifact
        run: |
          mkdir codedeploy_artifact
          zip -r ${{env.ARTIFACT_NAME}} codedeploy_artifact/
          ls -al
          pwd
          cd codedeploy_artifact
          pwd
          ls -al
          cd .. 
          pwd
          ls -al
